version: 0.2

env:
  variables:
    AWS_REGION: ap-northeast-2
    WEBSOCKET_REPO: 548334873638.dkr.ecr.ap-northeast-2.amazonaws.com/websocket

phases:
  install:
    commands:
      - echo 'ðŸ’¡ Docker ê¶Œí•œì€ Privileged ëª¨ë“œë¡œ ì œê³µë˜ë¯€ë¡œ runtime-versions í•„ìš” ì—†ìŒ'

  pre_build:
    commands:
      - echo âœ… ECR ë¡œê·¸ì¸...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $WEBSOCKET_REPO
      - export IMAGE_URI=${WEBSOCKET_REPO}:latest
      - echo ðŸ” Secrets Managerì—ì„œ í™˜ê²½íŒŒì¼ ê°€ì ¸ì˜¤ê¸°...
      - aws secretsmanager get-secret-value --secret-id sgmetro --query SecretString --output text > ./websocket/.env

  build:
    commands:
      - echo ðŸ›  websocket ì´ë¯¸ì§€ ë¹Œë“œ
      - docker build -t websocket ./websocket
      - docker tag websocket:latest $WEBSOCKET_REPO:latest


  post_build:
    commands:
      - echo ðŸš€ ECRì— ì´ë¯¸ì§€ í‘¸ì‹œ
      - docker push $WEBSOCKET_REPO:latest
      - echo Build completed on `date`
      - printf '[{"name":"websocket","imageUri":"%s"}]' $IMAGE_URI > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json