version: 0.2

env:
  variables:
    AWS_REGION: ap-northeast-2
    LOGSTASH_REPO: 548334873638.dkr.ecr.ap-northeast-2.amazonaws.com/logstash

phases:
  install:
    commands:
      - echo '💡 Docker 권한은 Privileged 모드로 제공되므로 runtime-versions 필요 없음'

  pre_build:
    commands:
      - echo ✅ ECR 로그인...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $LOGSTASH_REPO
      - export IMAGE_URI=${LOGSTASH_REPO}:latest
      - export IMAGE_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
  build:
    commands:
      - echo 🛠 logstash 이미지 빌드
      - docker build -t logstash ./logstash
      - docker tag logstash:latest $LOGSTASH_REPO:latest

  post_build:
    commands:
      - echo 🚀 ECR에 이미지 푸시
      - docker push $LOGSTASH_REPO:latest
      - echo Build completed on `date`
      - printf '[{"name":"logstash","imageUri":"%s"}]' $IMAGE_URI > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
