version: 0.2

env:
  variables:
    AWS_REGION: ap-northeast-2
    FRONTEND_REPO: 548334873638.dkr.ecr.ap-northeast-2.amazonaws.com/frontend
    
phases:
  install:
    commands:
      - echo '💡 Docker 권한은 Privileged 모드로 제공되므로 runtime-versions 필요 없음'

  pre_build:
    commands:
      - echo ✅ ECR 로그인...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $FRONTEND_REPO
      - export IMAGE_URI=${FRONTEND_REPO}:latest
      - echo 🔐 Secrets Manager에서 환경파일 가져오기...
      - echo "$(aws secretsmanager get-secret-value --secret-id sgmetro_frontend --query SecretString --output text)" | jq -r 'to_entries[] | "\(.key)=\(.value)"' > ./frontend/.env.production
      - echo "📄 .env.production 내용:"
      - cat ./frontend/.env.production

  build:
    commands:
      - echo 🛠 frontend 이미지 빌드
      - docker build -t frontend ./frontend
      - docker tag frontend:latest $FRONTEND_REPO:latest
  post_build:
    commands:
      - echo 🚀 ECR에 이미지 푸시
      - docker push $FRONTEND_REPO:latest
      - echo Build completed on `date`
      - printf '[{"name":"frontend","imageUri":"%s"}]' $IMAGE_URI > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
