version: 0.2

env:
  variables:
    AWS_REGION: ap-northeast-2
    KIBANA_REPO: 548334873638.dkr.ecr.ap-northeast-2.amazonaws.com/kibana

phases:
  install:
    commands:
      - echo 'ðŸ’¡ Docker ê¶Œí•œì€ Privileged ëª¨ë“œë¡œ ì œê³µë˜ë¯€ë¡œ runtime-versions í•„ìš” ì—†ìŒ'

  pre_build:
    commands:
      - echo âœ… ECR ë¡œê·¸ì¸...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $KIBANA_REPO
      - export IMAGE_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
  build:
    commands:
      - echo ðŸ›  kibana ì´ë¯¸ì§€ ë¹Œë“œ
      - docker build -t kibana ./kibana
      - docker tag kibana:latest $KIBANA_REPO:latest


  post_build:
    commands:
      - echo ðŸš€ ECRì— ì´ë¯¸ì§€ í‘¸ì‹œ
      - docker push $KIBANA_REPO:latest
      - echo Build completed on `date`
      - printf '[{"name":"sgmetro-kibana-service","imageUri":"%s"}]' $IMAGE_URI > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
