version: 0.2

env:
  variables:
    AWS_REGION: ap-northeast-2
    BACKEND_REPO: 548334873638.dkr.ecr.ap-northeast-2.amazonaws.com/backend

phases:
  install:
    commands:
      - echo 'ðŸ’¡ Docker ê¶Œí•œì€ Privileged ëª¨ë“œë¡œ ì œê³µë˜ë¯€ë¡œ runtime-versions í•„ìš” ì—†ìŒ'

  pre_build:
    commands:
      - echo âœ… ECR ë¡œê·¸ì¸...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $BACKEND_REPO
      - export IMAGE_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      - echo ðŸ” Secrets Managerì—ì„œ í™˜ê²½íŒŒì¼ ê°€ì ¸ì˜¤ê¸°...
      - aws secretsmanager get-secret-value --secret-id sgmetro --query SecretString --output text > ./backend/.env

  build:
    commands:
      - echo ðŸ›  backend ì´ë¯¸ì§€ ë¹Œë“œ
      - docker build -t backend ./backend
      - docker tag backend:latest $BACKEND_REPO:latest

  post_build:
    commands:
      - echo ðŸš€ ECRì— ì´ë¯¸ì§€ í‘¸ì‹œ
      - docker push $BACKEND_REPO:latest
      - echo Build completed on `date`
      - printf '[{"name":"sgmetro-api-service","imageUri":"%s"}]' $IMAGE_URI > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
